language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t andrejpopov/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true andrejpopov/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: eu-central-1
 app: "docker"
 env: "Docker-env"
 bucket_name: "proben"
 bucket_path: "docker"
 on:
  branch: main
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
  